blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions or General Support
    url: https://github.com/JosueBrenes/dApp-TrustBridge/discussions
    about: Please use Discussions for general feedback, help, or ideas that are not bugs or features.
